### ISSUE TITLE
8.9.73的qua对不上，能否使用

### ISSUE THREAD

**Issue by CatOverrun** [fuqiuluo/unidbg-fetch-qsign#199]
go-cqhttp的protocol version:
```json
{
    "apk_id": "com.tencent.mobileqq",
    "app_id": 537170996,
    "sub_app_id": 537170996,
    "app_key": "0S200MNJT807V3GE",
    "sort_version_name": "8.9.73.11945",
    "build_time": 1690371091,
    "apk_sign": "a6b745bf24a2c277527716f6f36eb68d",
    "sdk_version": "6.0.0.2553",
    "sso_version": 20,
    "misc_bitmap": 150470524,
    "main_sig_map": 16724722,
    "sub_sig_map": 66560,
    "dump_time": 1691057433,
    "qua": "V1_AND_SQ_8.9.73_4416_YYB_D",
    "protocol_type": 6
}
```
icqq的device.ts:
```yaml
{
        name: "A8.9.73.11945",
        version: "8.9.73.11945",
        ver: "8.9.73",
        buildtime: 1690371091,
        subid: 537171689,
        bitmap: 150470524,
        sdkver: "6.0.0.2553",
        qua: 'V1_AND_SQ_8.9.73_4416_YYB_D',
        ssover: 20,
}
```

两者使用的qua均为“V1_AND_SQ_8.9.73_4416_YYB_D'”
而我看到qsign里面的8.9.73的config里面的qua是“V1_AND_SQ_8.9.73_4354_YYB_D”

这是否可以用使用？
