### ISSUE TITLE
提供一个docker-compose的启动配置

### ISSUE THREAD

**Issue by RexQian** [fuqiuluo/unidbg-fetch-qsign#24]
丢一个使用jdk直接启动的docker-compose配置
可以考虑放reademe里

```
version: '2'

services:
  qsign:
    image: openjdk:11.0-jdk
    environment:
      TZ: Asia/Shanghai
    restart: always
    working_dir: /app
    # 修改android_id和go-cqhttp生成的配置一致
    command: bash bin/unidbg-fetch-qsign --port=8080 --count=1 --library=txlib/8.9.63 --android_id=someandroidid
    volumes:
      # 当前目录放置qsign的解压包
      - ./unidbg-fetch-qsign-1.0.5:/app
      # 当前目录放置txlib
      - ./unidbg-fetch-qsign/txlib:/app/txlib
    ports:
      # 按需调整宿主机端口
      - 8901:8080
```
