### ISSUE TITLE
使用docker-compose部署启动失败

### ISSUE THREAD

**Issue by StephenSSR** [fuqiuluo/unidbg-fetch-qsign#37]
使用readme里的docker-compose配置会缺少host启动失败，在修改为`bash bin/unidbg-fetch-qsign --host=0.0.0.0 --port=9090 --count=1 --library=txlib\8.9.63 --android_id=`后启动报错为```
Exception in thread "main" java.lang.IllegalStateException: libfekit.so file is illegal. Your path must include libfekit.so and libQSec.so!
        at MainKt.main(Main.kt:52)
```，但在txlib文件夹中已经放入相关so文件，配置目录为`/root/qsign`，so文件位置为`/root/qsign/txlib`
docker-compose.yml配置为
```
version: '2'
services:
  qsign:
    image: openjdk:11.0-jdk
    environment:
      TZ: Asia/Shanghai
    restart: always
    working_dir: /app
    # 按需修改相关参数
    command: bash bin/unidbg-fetch-qsign --host=0.0.0.0 --port=9090 --count=1 --library=txlib\8.9.63 --android_id=xxxxxxxxxxx
    volumes:
      # 当前目录放置qsign的解压包
      - ./unidbg-fetch-qsign:/app
      # 当前目录放置txlib
      - ./txlib:/app/txlib
    ports:
      # 按需调整宿主机端口
      - 9090:9090

```
