### ISSUE TITLE
[To Fix][Actions] Release tag actions not working

### ISSUE THREAD

**Issue by XZhouQD** [fuqiuluo/unidbg-fetch-qsign#82]
Github Actions:
- [x] On Pull Request
- [x] On Master Push
- [ ] On Release tag

Current Issue:
1. short tag
2. auto creation of release
3. auto upload assets

**Comment by CCA2878** [comment]
Auto release可以这么写（从编译软路由的脚本偷来的）
```
    - name: Upload firmware to release
      uses: softprops/action-gh-release@v1
      if: steps.tag.outputs.status == 'success' && !cancelled()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        body_path: release.txt
        files: ${{ env.FIRMWARE }}/*
```
